// sampleData.js

module.exports = {
  rooms: [
    { seatCapacity: 100, isAvailable: true },
    { seatCapacity: 80, isAvailable: true },
    { seatCapacity: 120, isAvailable: true },
    { seatCapacity: 60, isAvailable: true },
    { seatCapacity: 150, isAvailable: false }, // maybe one room under maintenance
  ],
  movies: [
    // 20 movies; mark 12 as now playing (isActive: true), 8 as coming soon (false)
    {
      title: "The Shawshank Redemption",
      description: "Two imprisoned men bond over a number of years …",
      duration: 142, // in minutes
      genre: "Drama",
      movie_rating: "R",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=NmzuHjWmXOc",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Godfather",
      description: "The aging patriarch of an organized crime dynasty …",
      duration: 175,
      genre: "Crime, Drama",
      movie_rating: "R",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=sY1S34973zA",
      movieImage: "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_.jpg",
    },
    {
      title: "The Dark Knight",
      description: "When the menace known as the Joker wreaks havoc …",
      duration: 152,
      genre: "Action, Crime, Drama",
      movie_rating: "PG-13",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Godfather Part II",
      description: "The early life and career of Vito Corleone …",
      duration: 202,
      genre: "Crime, Drama",
      movie_rating: "R",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=9O1Iy9od7-A",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "12 Angry Men",
      description: "A jury holdout attempts to prevent a miscarriage of justice …",
      duration: 96,
      genre: "Drama",
      movie_rating: "Approved", 
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=_13J_9B5jEk",
      movieImage: "https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "Schindler’s List",
      description: "In German-occupied Poland during World War II …",
      duration: 195,
      genre: "Biography, Drama, History",
      movie_rating: "R",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=gG22XNhtnoY",
      movieImage: "https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Lord of the Rings: The Return of the King",
      description: "Gandalf and Aragorn lead the World of Men …",
      duration: 201,
      genre: "Adventure, Drama, Fantasy",
      movie_rating: "PG-13",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "Pulp Fiction",
      description: "The lives of two mob hitmen, a boxer, …",
      duration: 154,
      genre: "Crime, Drama",
      movie_rating: "R",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
      movieImage: "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Lord of the Rings: The Fellowship of the Ring",
      description: "A meek Hobbit from the Shire … sets out to the Dark Lord’s realm …",
      duration: 178,
      genre: "Adventure, Drama, Fantasy",
      movie_rating: "PG-13",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=V75dMMIW2B4",
      movieImage: "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Lord of the Rings: The Two Towers",
      description: "While Frodo and Sam edge closer to Mordor …",
      duration: 179,
      genre: "Adventure, Drama, Fantasy",
      movie_rating: "PG-13",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=LbfMDwc4azU",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Good, the Bad and the Ugly",
      description: "A bounty hunting scam … during the American Civil War …",
      duration: 178,
      genre: "Western",
      movie_rating: "R",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=WCN5JJY_wiA",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "Fight Club",
      description: "An insomniac office worker … forms an underground fight club …",
      duration: 139,
      genre: "Drama",
      movie_rating: "R",
      language: "English",
      isActive: true,
      trailer: "https://www.youtube.com/watch?v=SUXWAEX2jlg",
      movieImage: "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "Forrest Gump",
      description: "The presidencies of Kennedy and Johnson … through the eyes of an Alabama man …",
      duration: 142,
      genre: "Drama, Romance",
      movie_rating: "PG-13",
      language: "English",
      isActive: false, // coming soon
      trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMGRhODhiMTAtNDUxMy00NTY1LTgyYmUtMTgwNzE2MGFlMWJmXkEyXkFqcGc@._V1_.jpg",
    },
    {
      title: "Inception",
      description: "A thief who steals corporate secrets … through dream-sharing technology …",
      duration: 148,
      genre: "Action, Adventure, Sci-Fi",
      movie_rating: "PG-13",
      language: "English",
      isActive: false,
      trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Empire Strikes Back",
      description: "After the Rebels are brutally overpowered …",
      duration: 124,
      genre: "Action, Adventure, Sci-Fi",
      movie_rating: "PG",
      language: "English",
      isActive: false,
      trailer: "https://www.youtube.com/watch?v=JNwNXF9Y6kY",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "The Silence of the Lambs",
      description: "A young FBI cadet … seeks the help … with an incarcerated cannibal …",
      duration: 118,
      genre: "Crime, Drama, Thriller",
      movie_rating: "R",
      language: "English",
      isActive: false,
      trailer: "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
      movieImage: "https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_.jpg",
    },
    {
      title: "Saving Private Ryan",
      description: "Following the Normandy Landings, …",
      duration: 169,
      genre: "Drama, War",
      movie_rating: "R",
      language: "English",
      isActive: false,
      trailer: "https://www.youtube.com/watch?v=2TejxhWkXpI",
      movieImage: "https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    },
    {
      title: "Spirited Away",
      description: "During her family’s move to the suburbs, a sullen 10-year-old girl … enters a world ruled by gods, witches, and spirits …",
      duration: 125,
      genre: "Animation, Adventure, Family",
      movie_rating: "PG",
      language: "Japanese",
      isActive: false,
      trailer: "https://www.youtube.com/watch?v=ByXuk9QqQk",
      movieImage: "https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_.jpg",
    },
    {
      title: "The Green Mile",
      description: "The lives of guards on Death Row are affected by one of their charges …",
      duration: 189,
      genre: "Crime, Drama, Fantasy",
      movie_rating: "R",
      language: "English",
      isActive: false,
      trailer: "https://www.youtube.com/watch?v=Ki4haFrqzmk",
      movieImage: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_FMjpg_UX1000_.jpg",
    },
  ],
  showTimings: [
  {
    movieTitle: "The Shawshank Redemption",
    roomIndex: 1,
    showDate: "2025-09-22T00:00:00.000Z",
    startTime: "2025-09-22T14:00:00.000Z",
    endTime: "2025-09-22T16:22:00.000Z"
  },
  {
    movieTitle: "The Shawshank Redemption",
    roomIndex: 2,
    showDate: "2025-09-22T00:00:00.000Z",
    startTime: "2025-09-22T18:00:00.000Z",
    endTime: "2025-09-22T20:22:00.000Z"
  },
  {
    movieTitle: "The Godfather",
    roomIndex: 1,
    showDate: "2025-09-22T00:00:00.000Z",
    startTime: "2025-09-22T15:00:00.000Z",
    endTime: "2025-09-22T17:55:00.000Z"
  },
  {
    movieTitle: "The Dark Knight",
    roomIndex: 3,
    showDate: "2025-09-22T00:00:00.000Z",
    startTime: "2025-09-22T20:00:00.000Z",
    endTime: "2025-09-22T22:32:00.000Z"
  },
  {
    movieTitle: "The Godfather Part II",
    roomIndex: 2,
    showDate: "2025-09-23T00:00:00.000Z",
    startTime: "2025-09-23T13:00:00.000Z",
    endTime: "2025-09-23T16:23:00.000Z"
  },
  {
    movieTitle: "12 Angry Men",
    roomIndex: 4,
    showDate: "2025-09-23T00:00:00.000Z",
    startTime: "2025-09-23T18:00:00.000Z",
    endTime: "2025-09-23T19:36:00.000Z"
  },
  {
    movieTitle: "Schindler’s List",
    roomIndex: 5,
    showDate: "2025-09-23T00:00:00.000Z",
    startTime: "2025-09-23T20:00:00.000Z",
    endTime: "2025-09-23T23:15:00.000Z"
  },
  {
    movieTitle: "The Lord of the Rings: The Return of the King",
    roomIndex: 1,
    showDate: "2025-09-24T00:00:00.000Z",
    startTime: "2025-09-24T12:00:00.000Z",
    endTime: "2025-09-24T15:21:00.000Z"
  },
  {
    movieTitle: "Pulp Fiction",
    roomIndex: 2,
    showDate: "2025-09-24T00:00:00.000Z",
    startTime: "2025-09-24T16:00:00.000Z",
    endTime: "2025-09-24T18:34:00.000Z"
  },
  {
    movieTitle: "The Lord of the Rings: The Fellowship of the Ring",
    roomIndex: 3,
    showDate: "2025-09-24T00:00:00.000Z",
    startTime: "2025-09-24T19:00:00.000Z",
    endTime: "2025-09-24T22:58:00.000Z"
  },
  {
    movieTitle: "The Lord of the Rings: The Two Towers",
    roomIndex: 4,
    showDate: "2025-09-22T00:00:00.000Z",
    startTime: "2025-09-22T13:00:00.000Z",
    endTime: "2025-09-22T15:59:00.000Z"
  },
  {
    movieTitle: "The Good, the Bad and the Ugly",
    roomIndex: 5,
    showDate: "2025-09-22T00:00:00.000Z",
    startTime: "2025-09-22T17:00:00.000Z",
    endTime: "2025-09-22T19:58:00.000Z"
  },
  {
    movieTitle: "Fight Club",
    roomIndex: 1,
    showDate: "2025-09-23T00:00:00.000Z",
    startTime: "2025-09-23T14:00:00.000Z",
    endTime: "2025-09-23T16:19:00.000Z"
  },
  {
    movieTitle: "Fight Club",
    roomIndex: 2,
    showDate: "2025-09-24T00:00:00.000Z",
    startTime: "2025-09-24T20:00:00.000Z",
    endTime: "2025-09-24T22:19:00.000Z"
  },
],
};
